name: CI
on:
  push:
    branches: [ master ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "::set-output name=test1::hello"
    - id: step2
      run: echo "::set-output name=test2::world"
    outputs:
      output1: ${{ steps.step1.outputs.test1 }}
      output4: ${{ steps.step2.outputs.test2 }}
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
