name: Test Action
on:
  push:
    branches: [ master ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Installing PHP
      run: echo 'test' > test.txt
    - name: git setting
      run: |
        git config --local user.email "test@example.com"
        git config --local user.name "akkey247"
    - name: Commit files
      run: |
        git add .
        git commit -m "test" -a
        git pull
        git push origin master
